# -*- coding: utf-8 -*-
"""aws demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_b5girsbv-6VMbdNiqyF4QCSFXNXFEf
"""

#read XL
import pandas as pd
df = pd.read_excel("mark.xlsx")
print(df)