# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BBQUIMDDOCvCZgw1kzTpFC5V0RLiTfO_
"""

a = 15
b = 12
c = a + b
print(c)